### ISSUE TITLE
模板图片生成处理问题

### ISSUE THREAD

**Issue by 892951522** [qrpcode/letsPPT#1]
![image](https://github.com/qrpcode/letsPPT/assets/25638381/16d067c4-a560-41e6-96a5-ee32c5250a99)
前端调用接口 /read/ppt/filePath

![image](https://github.com/qrpcode/letsPPT/assets/25638381/3396ce4b-eedf-4a20-8e57-0e03aade02c1)
 此处接口的处理一直在循环读取状态，但不知道状态的修改由哪出触发。

是还需要额外启动其他什么服务吗？

**Comment by qrpcode** [comment]
需要的，有一个exe，运行下pptBuilder.exe，在下面目录
https://github.com/qrpcode/letsPPT/tree/main/exe-gadget

这个是负责调用本地Office生成图片的（因为exe支持WPS生成，pptShow生成的只支持MSOffice，所以这样用的exe）
